import React, { useState, useContext } from "react";
import RestaurantList from '../components/restaurantList'
import { Button, Input} from "reactstrap"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Cookie from "js-cookie";

export default function Home() {   
  const [query, setQuery] = useState("");
  const checkUser = Cookie.get("user") ? Cookie.get("user") + "!" : '' ;
  const dtitle = "Welcome to Local Restaurant Hub " + checkUser ;

  return (
    <div className={styles.container}>
      <Head>
        <title>Restaurant App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          {dtitle}
        </h2>
       
           <div>
                 <Input
                     onChange={(e) => 
                      setQuery(e.target.value.toLocaleLowerCase())
                     }
                     value={query}
                 />
                 <Button color="primary">Search</Button>                   
           </div>
           <RestaurantList search={query} />
           
                      
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
